# Generated by Django 2.2.6 on 2019-11-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uniquewords',
            field=models.CharField(default='project', max_length=255),
        ),
    ]
