# Generated by Django 2.2.6 on 2019-11-02 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
