# Generated by Django 2.2.6 on 2019-11-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_favourite_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
