# Generated by Django 2.2.6 on 2019-11-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_delete_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
