# Generated by Django 2.2.6 on 2019-11-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorites',
            new_name='favourites',
        ),
    ]
